class FeedData {
  String gambar;
  String nama;
  String daerah;
  String waktu;
  List<String> bahan;
  List gambarBahan;
  List jumlahBahan;
  List Resep;
  List gambarBanner;

  FeedData({
    required this.gambar,
    required this.nama,
    required this.daerah,
    required this.waktu,
    required this.bahan,
    required this.gambarBahan,
    required this.jumlahBahan,
    required this.Resep,
    required this.gambarBanner,
  });
}

var feedDataFood = [
  FeedData(
    gambar:
        'https://www.resepkuerenyah.com/wp-content/uploads/2016/11/18.-resep-kue-serabi-tepung-beras.jpg',
    nama: 'Kue Serabi',
    daerah: 'Jawa Barat',
    waktu: '-',
    bahan: [
      'Daun pandan',
      'Tepung beras',
      'Garam',
      'kelapa parut',
      'Santan',
      'Gula pasir',
      'Gula merah sisir',
    ],
    jumlahBahan: [
      '2 Lembar',
      '150 g',
      'Secukupnya',
      '1/2 Butir',
      '250 ml',
      '15 g',
      '50 g',
    ],
    Resep: [
      'Didihkan santan dengan 2 lembar daun pandan',
      'Campur kelapa parut, tepung beras gula pasir dan garam aduk rata.',
      'Sajikan bersama dengan pelengkap.',
    ],
    gambarBahan: [
      'https://asset-a.grid.id/crop/0x0:0x0/x/photo/2021/03/25/daun-pandan-baru-2jpg-20210325114047.jpg',
      'https://cdns.klimg.com/merdeka.com/i/w/news/2017/03/02/818370/640x320/8-masker-dari-tepung-beras-untuk-kulit-cerah-tanpa-cela.jpg',
      'https://d1bpj0tv6vfxyp.cloudfront.net/ketahu5jenisgaramdanmanfaatnyauntukkesehatanhalodoc.jpg',
      'https://akcdn.detik.net.id/api/wm/2020/08/25/ilustrasi-kelapa-parut-1_169.jpeg',
      'https://www.alodokter.com/wp-content/uploads/2020/10/Tak-Berbahaya-Kenali-Manfaat-Santan-Lebih-Dekat-min.jpg',
      'https://d324bm9stwnv8c.cloudfront.net/Pemanis_Rendah_Kalori_Sebagai_Pengganti_Gula_Pasir,_Amankah-halodoc.jpg',
      'https://asset.kompas.com/crops/D3YU8grvTsCKEByMfszD7trEgyo=/0x23:700x373/780x390/data/photo/2020/07/11/5f094d0943a04.jpg',
    ],
    gambarBanner: [
      'https://www.resepkuerenyah.com/wp-content/uploads/2016/11/18.-resep-kue-serabi-tepung-beras.jpg',
      'http://3.bp.blogspot.com/-zcjRrqcwRv0/VnvTLbuRyqI/AAAAAAAACv0/C-QAai6RSsc/s1600/serabi%2Btepung%2Bberas.jpg',
      'http://kbu-cdn.com/dk/wp-content/uploads/serabi-manis.jpg',
    ],
  ),
  FeedData(
    gambar:
        'https://cdns.klimg.com/merdeka.com/i/w/news/2020/08/27/1213224/540x270/8-cara-membuat-bika-ambon-lezat-kenyal-legit-dan-mudah-dicoba-di-rumah.jpg',
    nama: 'Bika Ambon',
    daerah: 'Sulawesi Utara',
    waktu: '10 Jam',
    bahan: [
      'Santan kental',
      'Santan cair',
      'Daun jeruk, buang batangnya',
      'Batang serai',
      'Kunyit bubuk',
      'Air',
      'Tepung protein sedang',
      'Ragi instan',
      'Gula pasir',
      'Tepung sagu',
      'Tepung ketan',
      'Kuning telur',
      'Telur ayam utuh',
      'Bubuk vanili',
      'Garam'
    ],
    jumlahBahan: [
      '300 ml',
      '100 ml',
      '4 Lembar',
      '2',
      '1 sdm',
      '120 ml',
      '50 g',
      '8 g',
      '2 sdm',
      '200 g',
      '100 g',
      '50 g',
      8,
      '2 Butir',
      '1 sdt',
      '1/2 sdt'
    ],
    Resep: [
      'Campur tepung terigu, gula pasir, air dan ragi instan. Aduk rata, lalu diamkan selama 15 menit pada suhu ruang',
      'Rebus santan kental bersama santan cair, daun jeruk, serai, dan kunyit bubuk.',
      'Gunakan api kecil. Aduk-aduk sampai mendidih agar tidak pecah.',
      'Masukkan telur utuh, kuning telur, gula pasir, garam dan vanilla bubuk, aduk hingga mengembang kemudian masukkan tepung sagu dan tepung ketan, aduk.',
      'Masukkan bahan biang ke dalam bahan utama, aduk sampai rata kemudian masukkan bahan santan, aduk sampai rata lalu diamkan selama 2 jam.',
      'Setelah diistirahatkan, aduk kembali. Masukkan ke dalam loyang yg sudah di berikan minyak dan sudah di panaskan. Panggang dalam oven dengan suhu 180 derajat selama 35-40 menit dengan pintu oven sedikit terbuka.',
      'Jika bika ambon sudah matang, segera keluarkan dari oven.',
      'Tunggu sampai bika ambon dingin, lalu potong-potong dan sajikan.',
      'Sajikan bersama dengan pelengkap.',
    ],
    gambarBahan: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxjcqg2Q2vrHGkEI51oaw9Tul_VMXRWyEsw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyeYtNCoOMflivTBB53q6QsQHLavXpl-sWGA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjoVDy_maQWkwU-yczqEbOO_wZ1vV7n9OQA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSspnHIlPY9zdHRRmu79lHE7ZbfFZnFseRS7A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmDkZtbsIXPOTKwxAFd_jKhol5KmxWGJlVqQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZKSlhGLml4iia9CZaQv60BhxF-o6HNbRlw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9hbTH25VLWloyOnH8z17reRk4c184GzE4Q&usqp=CAU',
    ],
    gambarBanner: [
      'https://www.masakapahariini.com/wp-content/uploads/2018/09/cara-membuat-nasi-uduk-MAHI-1.jpg',
      'https://asset.kompas.com/crops/gbmG_rSPvjMvwT8KeYilWzAfOUI=/0x0:1000x667/750x500/data/photo/2021/02/21/6032066dc88e0.jpg',
      'https://asset.kompas.com/crops/z4FKlniytutq5RHVVr0pwN0gkFA=/102x41:957x610/750x500/data/photo/2021/02/21/6031fe29cdef2.jpg',
    ],
  ),
  FeedData(
    gambar:
        'https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:good,w_640,ar_16:9/v1566898918/jwgiwgsirs5vwzbobopu.jpg',
    nama: 'Gudeg Jawa',
    daerah: 'Jawa',
    waktu: '1 jam',
    bahan: [
      'Beras',
      'Santan kental',
      'Daun salam',
      'Cengkeh',
      'Serai',
      'Merica',
      'Garam',
    ],
    jumlahBahan: [
      300,
      450,
      2,
      2,
      2,
      'Secukupnya',
      'Secukupnya',
    ],
    Resep: [
      'Beras yang sudah dicuci kemudian dikukus selama 30 menit. Sisihkan',
      'Didihkan santan bersama dengan cengkeh, kayu manis, daun salam, serai, hingga harum kemudian saring',
      'Kemudian aduk nasi yang sudah aron bersama santan hingga santan meresap',
      'Kukus kembali nasi selama 45 menit',
      'Sajikan bersama dengan pelengkap.',
    ],
    gambarBahan: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxjcqg2Q2vrHGkEI51oaw9Tul_VMXRWyEsw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyeYtNCoOMflivTBB53q6QsQHLavXpl-sWGA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjoVDy_maQWkwU-yczqEbOO_wZ1vV7n9OQA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSspnHIlPY9zdHRRmu79lHE7ZbfFZnFseRS7A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmDkZtbsIXPOTKwxAFd_jKhol5KmxWGJlVqQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZKSlhGLml4iia9CZaQv60BhxF-o6HNbRlw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9hbTH25VLWloyOnH8z17reRk4c184GzE4Q&usqp=CAU',
    ],
    gambarBanner: [
      'https://www.masakapahariini.com/wp-content/uploads/2018/09/cara-membuat-nasi-uduk-MAHI-1.jpg',
      'https://asset.kompas.com/crops/gbmG_rSPvjMvwT8KeYilWzAfOUI=/0x0:1000x667/750x500/data/photo/2021/02/21/6032066dc88e0.jpg',
      'https://asset.kompas.com/crops/z4FKlniytutq5RHVVr0pwN0gkFA=/102x41:957x610/750x500/data/photo/2021/02/21/6031fe29cdef2.jpg',
    ],
  ),
  FeedData(
    gambar:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRw2BVNVZD7HL4Y5JY_8RvIxfhTFynRRQSew&usqp=CAU',
    nama: 'Ayam Betutu',
    daerah: 'Bali',
    waktu: '1 jam',
    bahan: [
      'Ayam kampung potong sesuai selera',
      'Jeruk nipis kucurkan untuk mengurangi amis lalu bilas',
      'Ketumbar',
      'Kemiri, sangrai',
      'Kunyit',
      'Cabe rawit merah',
      'Terasi matang',
      'Gula dan garam',
      'Bawang merah',
      'Bawang putih',
      'Serai',
      'Lengkuas',
      'Jahe',
    ],
    jumlahBahan: [
      '1 ekor',
      1,
      '1 sdm',
      4,
      '1 ruas',
      'Secukupnya(15 Recomended)',
      '1 sdm',
      'Secukupnya',
      10,
      6,
      '3 batang',
      '3 ruas',
      '3 ruas'
    ],
    Resep: [
      'Ayam yang sudah dibersihkan, bakar sebentar saja',
      'Tumis bumbu halus sampai harum lalu masukkan bumbu rajangan halus.. masukkan ayam aduk2 lalu beri air matang sampai menutupi ayam',
      'Masak sampai matang lalu beri gula dan garam, bila rasa sudah pas sajikan dengan nasi panas, plecing kangkung, dan sambal matah',
      'Sajikan bersama dengan pelengkap.',
    ],
    gambarBahan: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxjcqg2Q2vrHGkEI51oaw9Tul_VMXRWyEsw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyeYtNCoOMflivTBB53q6QsQHLavXpl-sWGA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjoVDy_maQWkwU-yczqEbOO_wZ1vV7n9OQA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSspnHIlPY9zdHRRmu79lHE7ZbfFZnFseRS7A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmDkZtbsIXPOTKwxAFd_jKhol5KmxWGJlVqQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZKSlhGLml4iia9CZaQv60BhxF-o6HNbRlw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9hbTH25VLWloyOnH8z17reRk4c184GzE4Q&usqp=CAU',
    ],
    gambarBanner: [
      'https://www.masakapahariini.com/wp-content/uploads/2018/09/cara-membuat-nasi-uduk-MAHI-1.jpg',
      'https://asset.kompas.com/crops/gbmG_rSPvjMvwT8KeYilWzAfOUI=/0x0:1000x667/750x500/data/photo/2021/02/21/6032066dc88e0.jpg',
      'https://asset.kompas.com/crops/z4FKlniytutq5RHVVr0pwN0gkFA=/102x41:957x610/750x500/data/photo/2021/02/21/6031fe29cdef2.jpg',
    ],
  ),
  FeedData(
    gambar:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRw2BVNVZD7HL4Y5JY_8RvIxfhTFynRRQSew&usqp=CAU',
    nama: 'Mie Aceh',
    daerah: 'Aceh',
    waktu: '-',
    bahan: [
      'Mie kering. Rebus matang. Tiriskan',
      'Bawang merah',
      'Bawang putih',
      'Cabe merah',
      'Cabe rawit',
      'Tomat',
      'Jahe',
      'Kemiri, sangrai',
      'Telur kocok',
      'Bubuk kari',
      'Kecap manis',
      'Kecap asin',
      'Air',
      'Garam dan gula',
      'Kol, sawi, seledri iris',
      'Penyedap bubuk',
      'Minyak goreng'
    ],
    jumlahBahan: [
      '250 g',
      6,
      4,
      7,
      10,
      1,
      '1 ruas',
      '4 butir',
      '2 butir',
      '1 sdm',
      '3 sdm',
      '2 sdm',
      '1 cangkir',
      'Secukupnya',
      'Secukupnya',
      'Secukupnya',
      'Secukupnya'
    ],
    Resep: [
      'Haluskan bahan - bahan sbb: cabe - cabean, duo bawang, jahe, kemiri dan tomat.',
      'Panaskan minyak, tumis bumbu halus sampai wangi. Masukkan telur. Aduk - aduk sampai rata dan telur kaku. Kalau ada tambahan lain spt ayam, irisan daging, udang atau lainnya silakan dimasukkan dalam tahapan ini.',
      'Masukkan sayur - sayuranan dan air kaldu. Tambahkan sisa bahan lainnya.',
      'Masukkan mie. Aduk rata. Check rasa sesuai selera. Angkat.',
      'Sajikan bersama dengan pelengkap.',
    ],
    gambarBahan: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxjcqg2Q2vrHGkEI51oaw9Tul_VMXRWyEsw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyeYtNCoOMflivTBB53q6QsQHLavXpl-sWGA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjoVDy_maQWkwU-yczqEbOO_wZ1vV7n9OQA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSspnHIlPY9zdHRRmu79lHE7ZbfFZnFseRS7A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmDkZtbsIXPOTKwxAFd_jKhol5KmxWGJlVqQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZKSlhGLml4iia9CZaQv60BhxF-o6HNbRlw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9hbTH25VLWloyOnH8z17reRk4c184GzE4Q&usqp=CAU',
    ],
    gambarBanner: [
      'https://www.masakapahariini.com/wp-content/uploads/2018/09/cara-membuat-nasi-uduk-MAHI-1.jpg',
      'https://asset.kompas.com/crops/gbmG_rSPvjMvwT8KeYilWzAfOUI=/0x0:1000x667/750x500/data/photo/2021/02/21/6032066dc88e0.jpg',
      'https://asset.kompas.com/crops/z4FKlniytutq5RHVVr0pwN0gkFA=/102x41:957x610/750x500/data/photo/2021/02/21/6031fe29cdef2.jpg',
    ],
  ),
  FeedData(
    gambar:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRw2BVNVZD7HL4Y5JY_8RvIxfhTFynRRQSew&usqp=CAU',
    nama: 'Ikan Asar',
    daerah: 'Maluku',
    waktu: '3 jam',
    bahan: [
      'Ikan komo (tongkol)',
      'Lembar daun pisang',
      'Garam',
      'Cabai',
      'Bawang merah',
      'Tomat',
      'Jeruk nipis',
    ],
    jumlahBahan: [
      1,
      'Beberapa',
      '3 sdm',
      3,
      3,
      1,
      1
    ],
    Resep: [
      'Bersihkan ikan, lalu olesi dengan garam',
      'Bungkus ikan dengan daun pisang.',
      'Panggang ikan hingga matang',
      'Iris-iris bumbu: cabai, tomat dan bawang merah diris, bubuhi dengan air jeruk nipis.',
      'Sajikan Ikan panggang bersama sambal jeruk dan tambah pelengkap',
    ],
    gambarBahan: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxjcqg2Q2vrHGkEI51oaw9Tul_VMXRWyEsw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyeYtNCoOMflivTBB53q6QsQHLavXpl-sWGA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjoVDy_maQWkwU-yczqEbOO_wZ1vV7n9OQA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSspnHIlPY9zdHRRmu79lHE7ZbfFZnFseRS7A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmDkZtbsIXPOTKwxAFd_jKhol5KmxWGJlVqQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZKSlhGLml4iia9CZaQv60BhxF-o6HNbRlw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9hbTH25VLWloyOnH8z17reRk4c184GzE4Q&usqp=CAU',
    ],
    gambarBanner: [
      'https://www.masakapahariini.com/wp-content/uploads/2018/09/cara-membuat-nasi-uduk-MAHI-1.jpg',
      'https://asset.kompas.com/crops/gbmG_rSPvjMvwT8KeYilWzAfOUI=/0x0:1000x667/750x500/data/photo/2021/02/21/6032066dc88e0.jpg',
      'https://asset.kompas.com/crops/z4FKlniytutq5RHVVr0pwN0gkFA=/102x41:957x610/750x500/data/photo/2021/02/21/6031fe29cdef2.jpg',
    ],
  ),
  FeedData(
    gambar:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRw2BVNVZD7HL4Y5JY_8RvIxfhTFynRRQSew&usqp=CAU',
    nama: 'Ayam Cincane',
    daerah: 'Kalimantan Timur',
    waktu: '-',
    bahan: [
      'Daging Ayam',
      'Bawang Putih',
      'Bawang Merah',
      'Terasi',
      'Serai',
      'Lengkuas',
      'Cabai Merah',
      'Cabai Rawit Hijau',
      'Gula Merah',
      'Garam',
      'Daun Salam',
      'Arang',
      'Minyak Goreng',
      'Jahe',
      'Air'
    ],
    jumlahBahan: [
      '1 Ekor',
      7,
      12,
      '1 sdm',
      '3 Buah',
      '4 cm',
      17,
      7,
      '2 sdm'
      'Secukupnya',
      '3 Lembar',
      'Secukupnya',
      '5 sdm',
      'Secukupnya',
      'Secukupnya'
    ],
    Resep: [
      'Rebus ayam terlebih dahulu untuk menghilangkan kotoran di awal',
      'Haluskan semua bumbu, kecuali, sere, lengkuas, daun salam, jahe. Panaskan minyak masukkan bumbu halus dan pelengkap tumis sampai harum.',
      'Masukkan ayam yang telah di rebus tumis hingga harum, masukkan air hingga memenuhi ayam, dan tambahkan bumbu halus.',
      'Biarkan ayam dalam bumbu, masak hingga kuah habis dan mulai mengering. Bakar diatas arang yang telah dipanaskan hingga matang. Angkat sajikan.',
      'Sajikan bersama dengan pelengkap.',
    ],
    gambarBahan: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxjcqg2Q2vrHGkEI51oaw9Tul_VMXRWyEsw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyeYtNCoOMflivTBB53q6QsQHLavXpl-sWGA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjoVDy_maQWkwU-yczqEbOO_wZ1vV7n9OQA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSspnHIlPY9zdHRRmu79lHE7ZbfFZnFseRS7A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmDkZtbsIXPOTKwxAFd_jKhol5KmxWGJlVqQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZKSlhGLml4iia9CZaQv60BhxF-o6HNbRlw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9hbTH25VLWloyOnH8z17reRk4c184GzE4Q&usqp=CAU',
    ],
    gambarBanner: [
      'https://www.masakapahariini.com/wp-content/uploads/2018/09/cara-membuat-nasi-uduk-MAHI-1.jpg',
      'https://asset.kompas.com/crops/gbmG_rSPvjMvwT8KeYilWzAfOUI=/0x0:1000x667/750x500/data/photo/2021/02/21/6032066dc88e0.jpg',
      'https://asset.kompas.com/crops/z4FKlniytutq5RHVVr0pwN0gkFA=/102x41:957x610/750x500/data/photo/2021/02/21/6031fe29cdef2.jpg',
    ],
  ),
  FeedData(
    gambar:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRw2BVNVZD7HL4Y5JY_8RvIxfhTFynRRQSew&usqp=CAU',
    nama: 'Ayam Taliwang',
    daerah: 'Nusa Tenggara Barat',
    waktu: '-',
    bahan: [
      'Ayam kampung',
      'Kecap manis',
      'Gula merah disisir',
      'Garam, gula dan air',
      'Bawang merah',
      'Bawang putih',
      'Cabe keriting merah',
      'Cabe rawit',
      'kencur',
      'Tomat',
      'Rebon / terasi'
    ],
    jumlahBahan: [
      '1 Ekor',
      '2 sdm',
      '1 sdm',
      'Secukupnya',
      15,
      7,
      15,
      15,
      '2 Ruas',
      1,
      '1 sdt'
    ],
    Resep: [
      'Tumis bumbu halus sampai harum dan matang',
      'Masukkan ayam. Aduk sampai berubah warna',
      'Tambahkan air, gula merah, garam, gula dan air. Ungkep ayam',
      'Masak sampai ayam empuk dan bumbu mengental. Tambahkan kecap manis',
      'Bakar ayam diatas arang sambil sesekali diolesi sisa bumbu.',
      'Sajikan bersama dengan pelengkap.'
    ],
    gambarBahan: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxjcqg2Q2vrHGkEI51oaw9Tul_VMXRWyEsw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyeYtNCoOMflivTBB53q6QsQHLavXpl-sWGA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjoVDy_maQWkwU-yczqEbOO_wZ1vV7n9OQA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSspnHIlPY9zdHRRmu79lHE7ZbfFZnFseRS7A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmDkZtbsIXPOTKwxAFd_jKhol5KmxWGJlVqQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZKSlhGLml4iia9CZaQv60BhxF-o6HNbRlw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9hbTH25VLWloyOnH8z17reRk4c184GzE4Q&usqp=CAU',
    ],
    gambarBanner: [
      'https://www.masakapahariini.com/wp-content/uploads/2018/09/cara-membuat-nasi-uduk-MAHI-1.jpg',
      'https://asset.kompas.com/crops/gbmG_rSPvjMvwT8KeYilWzAfOUI=/0x0:1000x667/750x500/data/photo/2021/02/21/6032066dc88e0.jpg',
      'https://asset.kompas.com/crops/z4FKlniytutq5RHVVr0pwN0gkFA=/102x41:957x610/750x500/data/photo/2021/02/21/6031fe29cdef2.jpg',
    ],
  ),
  FeedData(
    gambar:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRw2BVNVZD7HL4Y5JY_8RvIxfhTFynRRQSew&usqp=CAU',
    nama: 'Lapa - Lapa',
    daerah: 'Sulawesi Tenggara',
    waktu: '2 Jam',
    bahan: [
      'Beras',
      'Kelapa, parut halus dan peras untuk diambil santannya',
      'Garam halus',
      'Daun pisang',
      'Tali (dari pelepah pohon pisang)',
    ],
    jumlahBahan: [
      '1 kg',
      '2 Butir',
      '1/2 sdm',
      'Secukupnya',
      'Secukupnya',
    ],
    Resep: [
      'Beras dicuci sampai bersih kemudian dimasak bersama tambahan santan kelapa dan campuran secukupnya garam. Aduk merata dan masak sampai menjadi nasi aron.',
      'Angkat beras yang sudah menjadi nasi aron kemudian tuangkan secukupnya pada daun pisang dan bungkus dengan bentuk memanjang. Padatkan isiannya dan gulung rapih.',
      'Supaya bungkusannya tidak terbuka, silahkan anda ikat bungkusan daun pisangnya dengan tali dari pelepah pohon pisang yang sudah disiapkan sebelumnya.',
      'Setelah itu masukkan bungkusan daun pisang berisi nasi aron ke dalam perebusan dan rebus matang. proses ini dapat memakan waktu hingga 90 menit lamanya.',
      'Setelah dirasa matang dan isi dalam bungkusan daun pisang menjadi lapa-lapa, angkat dan tiriskan',
      'Sajikan bersama dengan pelengkap.',
    ],
    gambarBahan: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxjcqg2Q2vrHGkEI51oaw9Tul_VMXRWyEsw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyeYtNCoOMflivTBB53q6QsQHLavXpl-sWGA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjoVDy_maQWkwU-yczqEbOO_wZ1vV7n9OQA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSspnHIlPY9zdHRRmu79lHE7ZbfFZnFseRS7A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmDkZtbsIXPOTKwxAFd_jKhol5KmxWGJlVqQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZKSlhGLml4iia9CZaQv60BhxF-o6HNbRlw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9hbTH25VLWloyOnH8z17reRk4c184GzE4Q&usqp=CAU',
    ],
    gambarBanner: [
      'https://www.masakapahariini.com/wp-content/uploads/2018/09/cara-membuat-nasi-uduk-MAHI-1.jpg',
      'https://asset.kompas.com/crops/gbmG_rSPvjMvwT8KeYilWzAfOUI=/0x0:1000x667/750x500/data/photo/2021/02/21/6032066dc88e0.jpg',
      'https://asset.kompas.com/crops/z4FKlniytutq5RHVVr0pwN0gkFA=/102x41:957x610/750x500/data/photo/2021/02/21/6031fe29cdef2.jpg',
    ],
  ),
  FeedData(
    gambar:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRw2BVNVZD7HL4Y5JY_8RvIxfhTFynRRQSew&usqp=CAU',
    nama: 'Papeda Papua',
    daerah: 'Papua',
    waktu: '-',
    bahan: [
      'Tepung sagu',
      'Garam',
      'Kaldu ayam',
      'Air',
      'Bawang putih',
    ],
    jumlahBahan: [
      '1/4 kg',
      'Secukupnya',
      'Secukupnya',
      '4 Gelas',
      2,
    ],
    Resep: [
      'Didihkan 3 gelas air',
      'Campur tepung sagu,kaldu,garam,dan bwng putih yg telah di blender halus dgn 1gelas air,aduk di mangkok',
      'Perlahan tuang cairan sagu ke air mendidih aduh terus sampe meletup-letup',
      'Sajikan bersama dengan pelengkap.',
    ],
    gambarBahan: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxjcqg2Q2vrHGkEI51oaw9Tul_VMXRWyEsw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyeYtNCoOMflivTBB53q6QsQHLavXpl-sWGA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjoVDy_maQWkwU-yczqEbOO_wZ1vV7n9OQA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSspnHIlPY9zdHRRmu79lHE7ZbfFZnFseRS7A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmDkZtbsIXPOTKwxAFd_jKhol5KmxWGJlVqQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsZKSlhGLml4iia9CZaQv60BhxF-o6HNbRlw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM9hbTH25VLWloyOnH8z17reRk4c184GzE4Q&usqp=CAU',
    ],
    gambarBanner: [
      'https://www.masakapahariini.com/wp-content/uploads/2018/09/cara-membuat-nasi-uduk-MAHI-1.jpg',
      'https://asset.kompas.com/crops/gbmG_rSPvjMvwT8KeYilWzAfOUI=/0x0:1000x667/750x500/data/photo/2021/02/21/6032066dc88e0.jpg',
      'https://asset.kompas.com/crops/z4FKlniytutq5RHVVr0pwN0gkFA=/102x41:957x610/750x500/data/photo/2021/02/21/6031fe29cdef2.jpg',
    ],
  ),
];
