import 'package:proto/model/kategori_data.dart';

class DataProvinsi {
  var daerah = {
    'Aceh': aceh,
    'Sumatera Utara': aceh,
    'Sumatera Barat': aceh,
    'Riau': 'Pekanbaru',
    'Kepulauan Riau': aceh,
    'Jambi': jambi,
    'Sumatera Selatan': aceh,
    'Kepulauan Bangka Belitung': aceh,
    'Bengkulu': aceh,
    'Lampung': aceh,
    'DKI Jakarta ': jakarta,
    'Banten': aceh,
    // 'Jawa Barat': aceh,
    // 'Jawa Tengah': 'Semarang',
    // 'DI Yogyakarta': 'Yogyakarta',
    // 'Jawa Timur': 'Surabaya',
    // 'Bali': 'Denpasar',
    // 'Nusa Tenggara Barat': 'Mataram',
    // 'Nusa Tenggara Timur': 'Kupang',
    // 'Kalimantan Barat': 'Pontianak',
    // 'Kalimantan Tengah': 'Palangkaraya',
    // 'Provinsi Kalimantan Selatan': 'Banjarmasin',
    // 'Kalimantan Timur': 'Samarinda',
    // 'Kalimantan Utara': 'Tanjung Selor',
    // 'Sulawesi Utara': 'Manado',
    // 'Gorontalo': 'Gorontalo',
    // 'Sulawesi Tengah': 'Palu',
    // 'Sulawesi Barat': 'Mamuju',
    // 'Provinsi Sulawesi Selatan': 'Makassar',
    // 'Sulawesi Tenggara': 'Kendari',
    // 'Maluku': 'Ambon',
    // 'Maluku Utara': 'Sofifi',
    // 'Papua Barat': 'Manokwari',
    // 'Papua': 'Jayapura',
  };

  var pancingan = [
    'Aceh',
    'Sumatera Utara',
    'Sumatera Barat',
    'Riau',
    'Kepulauan Riau',
    'Jambi',
    'Sumatera Selatan',
    'Kepulauan Bangka Belitung',
    'Bengkulu',
    'Lampung',
    'DKI Jakarta',
    'Banten',
  ];
}
