import 'package:proto/model/kategori_data.dart';

class DataProvinsi {
  var daerah = {
    'Aceh': aceh,
    'Sumatera Utara': sumatra_utara,
    'Sumatera Barat': sumatra_barat,
    'Riau': riau,
    'Kepulauan Riau': kepulauan_riau,
    'Jambi': jambi,
    'Sumatera Selatan': sumatra_selatan,
    'Kepulauan Bangka Belitung': kepulauan_bangka_belitung,
    'Bengkulu': bengkulu,
    'Lampung': lampung,
    'DKI Jakarta ': jakarta,
    'Banten': banten,
    'Jawa Barat': jawa_barat,
    'Jawa Tengah': jawa_tengah,
    'DI Yogyakarta': yogyakarta,
    'Jawa Timur': 'Surabaya',
    'Bali': bali,
    'Nusa Tenggara Barat': 'Mataram',
    'Nusa Tenggara Timur': 'Kupang',
    // 'Kalimantan Barat': 'Pontianak',
    // 'Kalimantan Tengah': 'Palangkaraya',
    // 'Provinsi Kalimantan Selatan': 'Banjarmasin',
    // 'Kalimantan Timur': 'Samarinda',
    // 'Kalimantan Utara': 'Tanjung Selor',
    // 'Sulawesi Utara': 'Manado',
    // 'Gorontalo': 'Gorontalo',
    // 'Sulawesi Tengah': 'Palu',
    // 'Sulawesi Barat': 'Mamuju',
    // 'Provinsi Sulawesi Selatan': 'Makassar',
    // 'Sulawesi Tenggara': 'Kendari',
    // 'Maluku': 'Ambon',
    // 'Maluku Utara': 'Sofifi',
    // 'Papua Barat': 'Manokwari',
    // 'Papua': 'Jayapura',
  };

  var pancingan = [
    'Aceh',
    'Sumatera Utara',
    'Sumatera Barat',
    'Riau',
    'Kepulauan Riau',
    'Jambi',
    'Sumatera Selatan',
    'Kepulauan Bangka Belitung',
    'Bengkulu',
    'Lampung',
    'DKI Jakarta',
    'Banten',
    'Jawa Barat',
    'Jawa Tengah',
    'DI Yogyakarta',
    'Jawa Timur',
    'Bali',
  ];
}
