import 'package:proto/model/kategori_data.dart';

class DataProvinsi {
  var daerah = {
    'Aceh': aceh,
    'Sumatera Utara': 'Medan',
    'Sumatera Barat': 'Padang',
    'Riau': 'Pekanbaru',
    'Kepulauan Riau': 'Tanjungpinang',
    'Jambi': jambi,
    'Sumatera Selatan': 'Palembang',
    'Kepulauan Bangka Belitung': 'Pangkal Pinang',
    'Bengkulu': 'Bengkulu',
    'Lampung': 'Bandar Lampung',
    'DKI Jakarta ': jakarta,
    'Banten': 'Serang',
    'Jawa Barat': 'Bandung',
    'Jawa Tengah': 'Semarang',
    'DI Yogyakarta': 'Yogyakarta',
    'Jawa Timur': 'Surabaya',
    'Bali': 'Denpasar',
    'Nusa Tenggara Barat': 'Mataram',
    'Nusa Tenggara Timur': 'Kupang',
    'Kalimantan Barat': 'Pontianak',
    'Kalimantan Tengah': 'Palangkaraya',
    'Provinsi Kalimantan Selatan': 'Banjarmasin',
    'Kalimantan Timur': 'Samarinda',
    'Kalimantan Utara': 'Tanjung Selor',
    'Sulawesi Utara': 'Manado',
    'Gorontalo': 'Gorontalo',
    'Sulawesi Tengah': 'Palu',
    'Sulawesi Barat': 'Mamuju',
    'Provinsi Sulawesi Selatan': 'Makassar',
    'Sulawesi Tenggara': 'Kendari',
    'Maluku': 'Ambon',
    'Maluku Utara': 'Sofifi',
    'Papua Barat': 'Manokwari',
    'Papua': 'Jayapura',
  };
}
